# Native NGA-West2 GMPE equations generated from audit-only VBA.
# This file is generated by scripts/generate_ngaw2_gmpe_native.py.

.excel_col_number <- function(label) {
  chars <- strsplit(label, "", fixed = TRUE)[[1]]
  out <- 0
  for (ch in chars) {
    out <- out * 26 + utf8ToInt(ch) - 64
  }
  out
}

.cof <- function(model, period) {
  lookup_period <- if (model == "CB14" && as.numeric(period) == 0) 0.001 else as.numeric(period)
  data <- load_coefficients(model)
  rows <- data[abs(as.numeric(data$period_s) - lookup_period) < 1e-9, ]
  if (nrow(rows) == 0L) {
    stop(sprintf("No coefficients for %s period %s", model, period), call. = FALSE)
  }
  labels <- sub("^([A-Z]+).*$", "\\1", rows$source_cell)
  rows$source_col <- vapply(labels, .excel_col_number, numeric(1))
  rows <- rows[order(rows$source_col), ]
  values <- rows$value
  missing <- is.na(values)
  values[missing] <- rows$cached_value[missing]
  as.numeric(values)
}

pgar_calc <- function(m, rjb, u, rs, ns, region, t) {
  c1 <- 0
  c2 <- 0
  c3 <- 0
  counter <- 0
  dc3 <- 0
  dc3chtur <- 0
  dc3jpit <- 0
  e0 <- 0
  e1 <- 0
  e2 <- 0
  e3 <- 0
  e4 <- 0
  e5 <- 0
  e6 <- 0
  fm <- 0
  fp <- 0
  h <- 0
  mh <- 0
  mref <- 0
  pgar <- 0
  r <- 0
  rref <- 0
  ss <- 0
  cof <- .cof("BSSA14", t)
  e0 <- cof[[1]]
  e1 <- cof[[2]]
  e2 <- cof[[3]]
  e3 <- cof[[4]]
  e4 <- cof[[5]]
  e5 <- cof[[6]]
  e6 <- cof[[7]]
  mh <- cof[[8]]
  c1 <- cof[[9]]
  c2 <- cof[[10]]
  c3 <- cof[[11]]
  mref <- cof[[12]]
  rref <- cof[[13]]
  h <- cof[[14]]
  dc3 <- cof[[15]]
  dc3chtur <- cof[[16]]
  dc3jpit <- cof[[17]]
  if (ns == 0 && rs == 0 && u == 0) {
    ss <- 1
  } else {
    ss <- 0
  }
  if (m <= mh) {
    fm <- e0 * u + e1 * ss + e2 * ns + e3 * rs + e4 * (m - mh) + e5 * (m - mh) ^ 2
  } else {
    fm <- e0 * u + e1 * ss + e2 * ns + e3 * rs + e6 * (m - mh)
  }
  r <- sqrt(rjb ^ 2 + h ^ 2)
  if (region == 0) {
    fp <- (c1 + c2 * (m - mref)) * log(r / rref) + (c3 + dc3) * (r - rref)
  } else if (region == 3 || region == 5) {
    fp <- (c1 + c2 * (m - mref)) * log(r / rref) + (c3 + dc3chtur) * (r - rref)
  } else if (region == 1 || region == 4) {
    fp <- (c1 + c2 * (m - mref)) * log(r / rref) + (c3 + dc3jpit) * (r - rref)
  } else {
    fp <- (c1 + c2 * (m - mref)) * log(r / rref) + (c3 + dc3) * (r - rref)
  }
  pgar <- exp(fm + fp)
  return(pgar)
}

dz1_calc <- function(vs30, z1, region, t) {
  dz1 <- 0
  mz1 <- 0
  if (region == 1) {
    mz1 <- exp(-5.23 / 2 * log((vs30 ^ 2 + 412.39 ^ 2) / (1360 ^ 2 + 412.39 ^ 2))) / 1000
  } else {
    mz1 <- exp(-7.15 / 4 * log((vs30 ^ 4 + 570.94 ^ 4) / (1360 ^ 4 + 570.94 ^ 4))) / 1000
  }
  dz1 <- z1 - mz1
  return(dz1)
}

i_14_raw <- function(m, rrup, f, vs30, t) {
  a11 <- 0
  a12 <- 0
  a21 <- 0
  a22 <- 0
  a3 <- 0
  b11 <- 0
  b12 <- 0
  b21 <- 0
  b22 <- 0
  counter <- 0
  fatn <- 0
  fdis <- 0
  fflt <- 0
  fm <- 0
  fsite <- 0
  g <- 0
  ksi <- 0
  phi <- 0
  y <- 0
  cof <- .cof("I14", t)
  a11 <- cof[[1]]
  a21 <- cof[[2]]
  b11 <- cof[[3]]
  b21 <- cof[[4]]
  a12 <- cof[[5]]
  a22 <- cof[[6]]
  b12 <- cof[[7]]
  b22 <- cof[[8]]
  a3 <- cof[[9]]
  ksi <- cof[[10]]
  g <- cof[[11]]
  phi <- cof[[12]]
  if (m <= 6.75) {
    fm <- a21 * m + a3 * (8.5 - m) ^ 2
  } else {
    fm <- a22 * m + a3 * (8.5 - m) ^ 2
  }
  if (m <= 6.75) {
    fdis <- -(b11 + b21 * m) * log(rrup + 10)
  } else {
    fdis <- -(b12 + b22 * m) * log(rrup + 10)
  }
  if (vs30 < 1200) {
    fsite <- ksi * log(vs30)
  } else {
    fsite <- ksi * log(1200)
  }
  fatn <- g * rrup
  fflt <- phi * f
  if (m <= 6.75) {
    y <- exp(a11 + fm + fdis + fsite + fatn + fflt)
  } else {
    y <- exp(a12 + fm + fdis + fsite + fatn + fflt)
  }
  return(y)
}

i_14_stdev_raw <- function(m, t) {
  a11 <- 0
  a12 <- 0
  a21 <- 0
  a22 <- 0
  a3 <- 0
  b11 <- 0
  b12 <- 0
  b21 <- 0
  b22 <- 0
  counter <- 0
  g <- 0
  ksi <- 0
  phi <- 0
  sigma <- 0
  cof <- .cof("I14", t)
  a11 <- cof[[1]]
  a21 <- cof[[2]]
  b11 <- cof[[3]]
  b21 <- cof[[4]]
  a12 <- cof[[5]]
  a22 <- cof[[6]]
  b12 <- cof[[7]]
  b22 <- cof[[8]]
  a3 <- cof[[9]]
  ksi <- cof[[10]]
  g <- cof[[11]]
  phi <- cof[[12]]
  if (t <= 0.05) {
    if (m <= 5) {
      sigma <- 1.18 + 0.035 * log(0.05) - 0.06 * 5
    } else if (m >= 7.5) {
      sigma <- 1.18 + 0.035 * log(0.05) - 0.06 * 7.5
    } else {
      sigma <- 1.18 + 0.035 * log(0.05) - 0.06 * m
    }
  } else if (t >= 3) {
    if (m <= 5) {
      sigma <- 1.18 + 0.035 * log(3) - 0.06 * 5
    } else if (m >= 7.5) {
      sigma <- 1.18 + 0.035 * log(3) - 0.06 * 7.5
    } else {
      sigma <- 1.18 + 0.035 * log(3) - 0.06 * m
    }
  } else {
    if (m <= 5) {
      sigma <- 1.18 + 0.035 * log(t) - 0.06 * 5
    } else if (m >= 7.5) {
      sigma <- 1.18 + 0.035 * log(t) - 0.06 * 7.5
    } else {
      sigma <- 1.18 + 0.035 * log(t) - 0.06 * m
    }
  }
  return(sigma)
}

bssa_14_raw <- function(m, rjb, u, rs, ns, vs30, region, z1, pgar, t) {
  c <- 0
  c1 <- 0
  c2 <- 0
  c3 <- 0
  counter <- 0
  dc3 <- 0
  dc3chtur <- 0
  dc3jpit <- 0
  dfr <- 0
  dfv <- 0
  dz1 <- 0
  e0 <- 0
  e1 <- 0
  e2 <- 0
  e3 <- 0
  e4 <- 0
  e5 <- 0
  e6 <- 0
  f1 <- 0
  f2 <- 0
  f3 <- 0
  f4 <- 0
  f5 <- 0
  f6 <- 0
  f7 <- 0
  flin <- 0
  fm <- 0
  fnl <- 0
  fp <- 0
  fs <- 0
  fz1 <- 0
  h <- 0
  mh <- 0
  minv <- 0
  mref <- 0
  mz1 <- 0
  phi1 <- 0
  phi2 <- 0
  r <- 0
  r1 <- 0
  r2 <- 0
  rref <- 0
  ss <- 0
  tau1 <- 0
  tau2 <- 0
  v1 <- 0
  v2 <- 0
  vc <- 0
  vref <- 0
  y <- 0
  cof <- .cof("BSSA14", t)
  e0 <- cof[[1]]
  e1 <- cof[[2]]
  e2 <- cof[[3]]
  e3 <- cof[[4]]
  e4 <- cof[[5]]
  e5 <- cof[[6]]
  e6 <- cof[[7]]
  mh <- cof[[8]]
  c1 <- cof[[9]]
  c2 <- cof[[10]]
  c3 <- cof[[11]]
  mref <- cof[[12]]
  rref <- cof[[13]]
  h <- cof[[14]]
  dc3 <- cof[[15]]
  dc3chtur <- cof[[16]]
  dc3jpit <- cof[[17]]
  c <- cof[[18]]
  vc <- cof[[19]]
  vref <- cof[[20]]
  f1 <- cof[[21]]
  f3 <- cof[[22]]
  f4 <- cof[[23]]
  f5 <- cof[[24]]
  f6 <- cof[[25]]
  f7 <- cof[[26]]
  r1 <- cof[[27]]
  r2 <- cof[[28]]
  dfr <- cof[[29]]
  dfv <- cof[[30]]
  v1 <- cof[[31]]
  v2 <- cof[[32]]
  phi1 <- cof[[33]]
  phi2 <- cof[[34]]
  tau1 <- cof[[35]]
  tau2 <- cof[[36]]
  if (ns == 0 && rs == 0 && u == 0) {
    ss <- 1
  } else {
    ss <- 0
  }
  if (m <= mh) {
    fm <- e0 * u + e1 * ss + e2 * ns + e3 * rs + e4 * (m - mh) + e5 * (m - mh) ^ 2
  } else {
    fm <- e0 * u + e1 * ss + e2 * ns + e3 * rs + e6 * (m - mh)
  }
  r <- sqrt(rjb ^ 2 + h ^ 2)
  if (region == 0) {
    fp <- (c1 + c2 * (m - mref)) * log(r / rref) + (c3 + dc3) * (r - rref)
  } else if (region == 3 || region == 5) {
    fp <- (c1 + c2 * (m - mref)) * log(r / rref) + (c3 + dc3chtur) * (r - rref)
  } else if (region == 1 || region == 4) {
    fp <- (c1 + c2 * (m - mref)) * log(r / rref) + (c3 + dc3jpit) * (r - rref)
  } else {
    fp <- (c1 + c2 * (m - mref)) * log(r / rref) + (c3 + dc3) * (r - rref)
  }
  if (vs30 <= vc) {
    flin <- c * log(vs30 / vref)
  } else {
    flin <- c * log(vc / vref)
  }
  if (vs30 < 760) {
    minv <- vs30
  } else {
    minv <- 760
  }
  f2 <- f4 * ((exp(f5 * (minv - 360))) - exp(f5 * (760 - 360)))
  fnl <- f1 + f2 * log((pgar + f3) / f3)
  fnl <- f1 + (f4 * ((exp(f5 * (minv - 360))) - exp(f5 * (760 - 360)))) * log((pgar + f3) / f3)
  if (region == 0) {
    mz1 <- exp(-7.15 / 4 * log((vs30 ^ 4 + 570.94 ^ 4) / (1360 ^ 4 + 570.94 ^ 4))) / 1000
  } else if (region == 1) {
    mz1 <- exp(-5.23 / 2 * log((vs30 ^ 2 + 412.39 ^ 2) / (1360 ^ 2 + 412.39 ^ 2))) / 1000
  } else {
    mz1 <- exp(-7.15 / 4 * log((vs30 ^ 4 + 570.94 ^ 4) / (1360 ^ 4 + 570.94 ^ 4))) / 1000
  }
  dz1 <- z1 - mz1
  if (z1 == 999) {
    dz1 <- 0
  } else {
    dz1 <- dz1
  }
  if (t < 0.65) {
    fz1 <- 0
  } else if (dz1 <= f7 / f6) {
    fz1 <- f6 * dz1
  } else if (dz1 > f7 / f6) {
    fz1 <- f7
  } else {
    fz1 <- 0
  }
  if (z1 == 999) {
    fz1 <- 0
  } else {
    fz1 <- fz1
  }
  fs <- flin + fnl
  y <- exp(fm + fp + fs + fz1)
  return(y)
}

bssa14_stdev_raw <- function(m, rjb, vs30, t) {
  c <- 0
  c1 <- 0
  c2 <- 0
  c3 <- 0
  counter <- 0
  dc3 <- 0
  dc3chtur <- 0
  dc3jpit <- 0
  dfr <- 0
  dfv <- 0
  e0 <- 0
  e1 <- 0
  e2 <- 0
  e3 <- 0
  e4 <- 0
  e5 <- 0
  e6 <- 0
  f1 <- 0
  f3 <- 0
  f4 <- 0
  f5 <- 0
  f6 <- 0
  f7 <- 0
  h <- 0
  mh <- 0
  mref <- 0
  phi <- 0
  phi1 <- 0
  phi2 <- 0
  phim <- 0
  phimr <- 0
  r1 <- 0
  r2 <- 0
  rref <- 0
  sigma <- 0
  tau1 <- 0
  tau2 <- 0
  taum <- 0
  v1 <- 0
  v2 <- 0
  vc <- 0
  vref <- 0
  cof <- .cof("BSSA14", t)
  e0 <- cof[[1]]
  e1 <- cof[[2]]
  e2 <- cof[[3]]
  e3 <- cof[[4]]
  e4 <- cof[[5]]
  e5 <- cof[[6]]
  e6 <- cof[[7]]
  mh <- cof[[8]]
  c1 <- cof[[9]]
  c2 <- cof[[10]]
  c3 <- cof[[11]]
  mref <- cof[[12]]
  rref <- cof[[13]]
  h <- cof[[14]]
  dc3 <- cof[[15]]
  dc3chtur <- cof[[16]]
  dc3jpit <- cof[[17]]
  c <- cof[[18]]
  vc <- cof[[19]]
  vref <- cof[[20]]
  f1 <- cof[[21]]
  f3 <- cof[[22]]
  f4 <- cof[[23]]
  f5 <- cof[[24]]
  f6 <- cof[[25]]
  f7 <- cof[[26]]
  r1 <- cof[[27]]
  r2 <- cof[[28]]
  dfr <- cof[[29]]
  dfv <- cof[[30]]
  v1 <- cof[[31]]
  v2 <- cof[[32]]
  phi1 <- cof[[33]]
  phi2 <- cof[[34]]
  tau1 <- cof[[35]]
  tau2 <- cof[[36]]
  if (m <= 4.5) {
    taum <- tau1
  } else if (m > 4.5 && m < 5.5) {
    taum <- tau1 + (tau2 - tau1) * (m - 4.5)
  } else {
    taum <- tau2
  }
  if (m <= 4.5) {
    phim <- phi1
  } else if (m > 4.5 && m < 5.5) {
    phim <- phi1 + (phi2 - phi1) * (m - 4.5)
  } else {
    phim <- phi2
  }
  if (rjb <= r1) {
    phimr <- phim
  } else if (rjb > r1 && rjb <= r2) {
    phimr <- phim + dfr * (log(rjb / r1) / (log(r2 / r1)))
  } else {
    phimr <- phim + dfr
  }
  if (vs30 >= v2) {
    phi <- phimr
  } else if (vs30 >= v1 && vs30 <= v2) {
    phi <- phimr - dfv * (log(v2 / vs30) / (log(v2 / v1)))
  } else {
    phi <- phimr - dfv
  }
  sigma <- sqrt(taum ^ 2 + phi ^ 2)
  return(sigma)
}

a1100_cb <- function(m, rrup, rjb, rx, frv, fnm, fhw, w, delta, ztor, z25, zhyp, ztord, wd, zhypd, region, t) {
  a1100 <- 0
  a2 <- 0
  c <- 0
  c0 <- 0
  c1 <- 0
  c10 <- 0
  c11 <- 0
  c12 <- 0
  c13 <- 0
  c14 <- 0
  c15 <- 0
  c16 <- 0
  c17 <- 0
  c18 <- 0
  c19 <- 0
  c2 <- 0
  c20 <- 0
  c3 <- 0
  c4 <- 0
  c5 <- 0
  c6 <- 0
  c7 <- 0
  c8 <- 0
  c9 <- 0
  counter <- 0
  dc20 <- 0
  dc20ca <- 0
  dc20ch <- 0
  dc20jp <- 0
  f1_rx <- 0
  f2_rx <- 0
  f2x <- 0
  fatn <- 0
  fdip <- 0
  fdis <- 0
  fflt <- 0
  ffltf <- 0
  ffltm <- 0
  fhng <- 0
  fhngm <- 0
  fhngr <- 0
  fhngrx <- 0
  fhngs <- 0
  fhngz <- 0
  fhyp <- 0
  fhyph <- 0
  fhypm <- 0
  fmag <- 0
  fsed <- 0
  h1 <- 0
  h2 <- 0
  h3 <- 0
  h4 <- 0
  h5 <- 0
  h6 <- 0
  k1 <- 0
  k2 <- 0
  k3 <- 0
  maxr <- 0
  n <- 0
  pi <- 0
  r1 <- 0
  r2 <- 0
  sj <- 0
  y <- 0
  z25r <- 0
  cof <- .cof("CB14", t)
  c0 <- cof[[1]]
  c1 <- cof[[2]]
  c2 <- cof[[3]]
  c3 <- cof[[4]]
  c4 <- cof[[5]]
  c5 <- cof[[6]]
  c6 <- cof[[7]]
  c7 <- cof[[8]]
  c8 <- cof[[9]]
  c9 <- cof[[10]]
  c10 <- cof[[11]]
  c11 <- cof[[12]]
  c12 <- cof[[13]]
  c13 <- cof[[14]]
  c14 <- cof[[15]]
  c15 <- cof[[16]]
  c16 <- cof[[17]]
  c17 <- cof[[18]]
  c18 <- cof[[19]]
  c19 <- cof[[20]]
  c20 <- cof[[21]]
  dc20ca <- cof[[22]]
  dc20jp <- cof[[23]]
  dc20ch <- cof[[24]]
  a2 <- cof[[25]]
  h1 <- cof[[26]]
  h2 <- cof[[27]]
  h3 <- cof[[28]]
  h4 <- cof[[29]]
  h5 <- cof[[30]]
  h6 <- cof[[31]]
  k1 <- cof[[32]]
  k2 <- cof[[33]]
  k3 <- cof[[34]]
  c <- cof[[35]]
  n <- cof[[36]]
  pi <- 4 * atan(1)
  if (region == 1) {
    sj <- 1
  } else {
    sj <- 0
  }
  if (ztor == 999) {
    ztor <- ztord
  } else {
    ztor <- ztor
  }
  if (zhyp == 999) {
    zhyp <- zhypd
  } else {
    zhyp <- zhyp
  }
  if (w == 999) {
    zhyp <- 9
  } else {
    zhyp <- zhyp
  }
  if (w == 999) {
    w <- wd
  } else {
    w <- w
  }
  z25r <- (1 - sj) * exp(7.089 - 1.144 * log(1100)) + sj * exp(5.359 - 1.102 * log(1100))
  if (z25 == 999) {
    z25 <- z25r
  } else {
    z25 <- z25
  }
  if (m <= 4.5) {
    fmag <- (c1 * m)
  } else if (m <= 5.5) {
    fmag <- (c1 * m) + (c2 * (m - 4.5))
  } else if (m <= 6.5) {
    fmag <- (c1 * m) + (c2 * (m - 4.5)) + (c3 * (m - 5.5))
  } else if (m > 6.5) {
    fmag <- (c1 * m) + (c2 * (m - 4.5)) + (c3 * (m - 5.5)) + (c4 * (m - 6.5))
  }
  fdis <- ((c5 + (c6 * m)) * (log(sqrt((rrup * rrup) + (c7 * c7)))))
  ffltf <- (c8 * frv) + (c9 * fnm)
  if (m <= 4.5) {
    ffltm <- 0
  } else if (m <= 5.5) {
    ffltm <- m - 4.5
  } else if (m > 5.5) {
    ffltm <- 1
  }
  fflt <- ffltf * ffltm
  r1 <- w * cos(delta * pi / 180)
  r2 <- 62 * m - 350
  f1_rx <- h1 + h2 * (rx / r1) + h3 * (rx / r1) ^ 2
  f2_rx <- h4 + h5 * ((rx - r1) / (r2 - r1)) + h6 * ((rx - r1) / (r2 - r1)) ^ 2
  if (f2_rx > 0) {
    maxr <- f2_rx
  } else {
    maxr <- 0
  }
  if (fhw == 0) {
    fhngrx <- 0
  } else if (rx < r1 && fhw == 1) {
    fhngrx <- f1_rx
  } else if (rx >= r1 && fhw == 1) {
    fhngrx <- maxr
  }
  if (rrup == 0) {
    fhngr <- 1
  } else if (rrup > 0) {
    fhngr <- (rrup - rjb) / rrup
  }
  if (f2_rx > 0) {
    f2x <- f2_rx
  } else {
    f2x <- 0
  }
  if (m <= 5.5) {
    fhngm <- 0
  } else if (m <= 6.5) {
    fhngm <- (m - 5.5) * (1 + a2 * (m - 6.5))
  } else if (m > 6.5) {
    fhngm <- 1 + a2 * (m - 6.5)
  }
  if (ztor < 16.66) {
    fhngz <- 1 - 0.06 * ztor
  } else if (ztor >= 16.66) {
    fhngz <- 0
  }
  fhngs <- (90 - delta) / 45
  fhng <- c10 * fhngrx * fhngr * fhngm * fhngz * fhngs
  if (z25 <= 1) {
    fsed <- (c14 + c15 * sj) * (z25 - 1)
  } else if (z25 > 1 && z25 <= 3) {
    fsed <- 0
  } else {
    fsed <- c16 * k3 * exp(-0.75) * (1 - exp(-0.25 * (z25 - 3)))
  }
  if (zhyp <= 7) {
    fhyph <- 0
  } else if (zhyp > 7 && zhyp <= 20) {
    fhyph <- zhyp - 7
  } else {
    fhyph <- 13
  }
  if (m <= 5.5) {
    fhypm <- c17
  } else if (m > 5.5 && m <= 6.5) {
    fhypm <- c17 + (c18 - c17) * (m - 5.5)
  } else {
    fhypm <- c18
  }
  fhyp <- fhyph * fhypm
  if (m <= 4.5) {
    fdip <- c19 * delta
  } else if (m > 4.5 && m <= 5.5) {
    fdip <- c19 * (5.5 - m) * delta
  } else {
    fdip <- 0
  }
  if (region == 0) {
    dc20 <- dc20ca
  } else if (region == 1 || region == 4) {
    dc20 <- dc20jp
  } else if (region == 3) {
    dc20 <- dc20ch
  } else {
    dc20 <- dc20ca
  }
  if (rrup > 80) {
    fatn <- (c20 + dc20) * (rrup - 80)
  } else if (rrup <= 80) {
    fatn <- 0
  }
  if (z25r < 1) {
    a1100 <- c0 + fmag + fdis + fflt + fhng + fhyp + fdip + fatn +      (c11 + k2 * n) * log(1100 / k1) + sj * (c13 + k2 * n) * log(1100 / k1) +      (c14 + sj * c15) * (z25r - 1)
  } else if (z25r > 3) {
    a1100 <- c0 + fmag + fdis + fflt + fhng + fhyp + fdip + fatn +      (c11 + k2 * n) * log(1100 / k1) + sj * (c13 + k2 * n) * log(1100 / k1) +      c16 * k3 * exp(-0.75) * (1 - exp(-0.25 * (z25r - 3)))
  } else {
    a1100 <- c0 + fmag + fdis + fflt + fhng + fhyp + fdip + fatn +      (c11 + k2 * n) * log(1100 / k1) + sj * (c13 + k2 * n) * log(1100 / k1)
  }
  y <- exp(a1100)
  return(y)
}

cb_14_raw <- function(m, rrup, rjb, rx, frv, fnm, fhw, ztor, w, delta, vs30, z25, zhyp, ztord, wd, zhypd, region, a, t) {
  a2 <- 0
  c <- 0
  c0 <- 0
  c1 <- 0
  c10 <- 0
  c11 <- 0
  c12 <- 0
  c13 <- 0
  c14 <- 0
  c15 <- 0
  c16 <- 0
  c17 <- 0
  c18 <- 0
  c19 <- 0
  c2 <- 0
  c20 <- 0
  c3 <- 0
  c4 <- 0
  c5 <- 0
  c6 <- 0
  c7 <- 0
  c8 <- 0
  c9 <- 0
  counter <- 0
  dc20 <- 0
  dc20ca <- 0
  dc20ch <- 0
  dc20jp <- 0
  f1_rx <- 0
  f2_rx <- 0
  f2x <- 0
  fatn <- 0
  fdip <- 0
  fdis <- 0
  fflt <- 0
  ffltf <- 0
  ffltm <- 0
  fhng <- 0
  fhngm <- 0
  fhngr <- 0
  fhngrx <- 0
  fhngs <- 0
  fhngz <- 0
  fhyp <- 0
  fhyph <- 0
  fhypm <- 0
  fmag <- 0
  fsed <- 0
  fsite <- 0
  fsitej <- 0
  h1 <- 0
  h2 <- 0
  h3 <- 0
  h4 <- 0
  h5 <- 0
  h6 <- 0
  k1 <- 0
  k2 <- 0
  k3 <- 0
  maxr <- 0
  median <- 0
  n <- 0
  phi1 <- 0
  phi2 <- 0
  phic <- 0
  philnaf <- 0
  pi <- 0
  r1 <- 0
  r2 <- 0
  ro <- 0
  sj <- 0
  sjp <- 0
  tau1 <- 0
  tau2 <- 0
  y <- 0
  ypgacb <- 0
  cof <- .cof("CB14", t)
  c0 <- cof[[1]]
  c1 <- cof[[2]]
  c2 <- cof[[3]]
  c3 <- cof[[4]]
  c4 <- cof[[5]]
  c5 <- cof[[6]]
  c6 <- cof[[7]]
  c7 <- cof[[8]]
  c8 <- cof[[9]]
  c9 <- cof[[10]]
  c10 <- cof[[11]]
  c11 <- cof[[12]]
  c12 <- cof[[13]]
  c13 <- cof[[14]]
  c14 <- cof[[15]]
  c15 <- cof[[16]]
  c16 <- cof[[17]]
  c17 <- cof[[18]]
  c18 <- cof[[19]]
  c19 <- cof[[20]]
  c20 <- cof[[21]]
  dc20ca <- cof[[22]]
  dc20jp <- cof[[23]]
  dc20ch <- cof[[24]]
  a2 <- cof[[25]]
  h1 <- cof[[26]]
  h2 <- cof[[27]]
  h3 <- cof[[28]]
  h4 <- cof[[29]]
  h5 <- cof[[30]]
  h6 <- cof[[31]]
  k1 <- cof[[32]]
  k2 <- cof[[33]]
  k3 <- cof[[34]]
  c <- cof[[35]]
  n <- cof[[36]]
  phi1 <- cof[[37]]
  phi2 <- cof[[38]]
  tau1 <- cof[[39]]
  tau2 <- cof[[40]]
  philnaf <- cof[[41]]
  phic <- cof[[42]]
  ro <- cof[[43]]
  pi <- 4 * atan(1)
  if (region == 1) {
    sj <- 1
  } else {
    sj <- 0
  }
  if (ztor == 999) {
    ztor <- ztord
  } else {
    ztor <- ztor
  }
  if (zhyp == 999) {
    zhyp <- zhypd
  } else {
    zhyp <- zhyp
  }
  if (w == 999) {
    zhyp <- 9
  } else {
    zhyp <- zhyp
  }
  if (w == 999) {
    w <- wd
  } else {
    w <- w
  }
  if (m <= 4.5) {
    fmag <- (c1 * m)
  } else if (m <= 5.5) {
    fmag <- (c1 * m) + (c2 * (m - 4.5))
  } else if (m <= 6.5) {
    fmag <- (c1 * m) + (c2 * (m - 4.5)) + (c3 * (m - 5.5))
  } else if (m > 6.5) {
    fmag <- (c1 * m) + (c2 * (m - 4.5)) + (c3 * (m - 5.5)) + (c4 * (m - 6.5))
  }
  fdis <- ((c5 + (c6 * m)) * (log(sqrt((rrup * rrup) + (c7 * c7)))))
  ffltf <- (c8 * frv) + (c9 * fnm)
  if (m <= 4.5) {
    ffltm <- 0
  } else if (m <= 5.5) {
    ffltm <- m - 4.5
  } else if (m > 5.5) {
    ffltm <- 1
  }
  fflt <- ffltf * ffltm
  r1 <- w * cos(delta * pi / 180)
  r2 <- 62 * m - 350
  f1_rx <- h1 + h2 * (rx / r1) + h3 * (rx / r1) ^ 2
  f2_rx <- h4 + h5 * ((rx - r1) / (r2 - r1)) + h6 * ((rx - r1) / (r2 - r1)) ^ 2
  if (f2_rx > 0) {
    maxr <- f2_rx
  } else {
    maxr <- 0
  }
  if (fhw == 0) {
    fhngrx <- 0
  } else if (rx < r1 && fhw == 1) {
    fhngrx <- f1_rx
  } else if (rx >= r1 && fhw == 1) {
    fhngrx <- maxr
  }
  if (rrup == 0) {
    fhngr <- 1
  } else if (rrup > 0) {
    fhngr <- (rrup - rjb) / rrup
  }
  if (f2_rx > 0) {
    f2x <- f2_rx
  } else {
    f2x <- 0
  }
  if (m <= 5.5) {
    fhngm <- 0
  } else if (m <= 6.5) {
    fhngm <- (m - 5.5) * (1 + a2 * (m - 6.5))
  } else if (m > 6.5) {
    fhngm <- 1 + a2 * (m - 6.5)
  }
  if (ztor < 16.66) {
    fhngz <- 1 - 0.06 * ztor
  } else if (ztor >= 16.66) {
    fhngz <- 0
  }
  fhngs <- (90 - delta) / 45
  fhng <- c10 * fhngrx * fhngr * fhngm * fhngz * fhngs
  if (region == 1) {
    sjp <- 1
  } else {
    sjp <- 0
  }
  if (vs30 <= k1) {
    fsite <- c11 * log(vs30 / k1) + k2 * (log(a + c * (vs30 / k1) ^ n) - log(a + c))
  } else {
    fsite <- (c11 + k2 * n) * log(vs30 / k1)
  }
  if (vs30 <= 200) {
    fsitej <- (c12 + k2 * n) * (log(vs30 / k1) - log(200 / k1)) * sjp
  } else {
    fsitej <- (c13 + k2 * n) * log(vs30 / k1) * sjp
  }
  fsite <- fsite + fsitej
  if (z25 == 999) {
    if (region == 1) {
      z25 <- exp(5.359 - 1.102 * log(vs30))
    } else {
      z25 <- exp(7.089 - 1.144 * log(vs30))
    }
  }
  if (z25 <= 1) {
    fsed <- (c14 + c15 * sj) * (z25 - 1)
  } else if (z25 > 1 && z25 <= 3) {
    fsed <- 0
  } else {
    fsed <- c16 * k3 * exp(-0.75) * (1 - exp(-0.25 * (z25 - 3)))
  }
  if (zhyp <= 7) {
    fhyph <- 0
  } else if (zhyp > 7 && zhyp <= 20) {
    fhyph <- zhyp - 7
  } else {
    fhyph <- 13
  }
  if (m <= 5.5) {
    fhypm <- c17
  } else if (m > 5.5 && m <= 6.5) {
    fhypm <- c17 + (c18 - c17) * (m - 5.5)
  } else {
    fhypm <- c18
  }
  fhyp <- fhyph * fhypm
  if (m <= 4.5) {
    fdip <- c19 * delta
  } else if (m > 4.5 && m <= 5.5) {
    fdip <- c19 * (5.5 - m) * delta
  } else {
    fdip <- 0
  }
  if (region == 0) {
    dc20 <- dc20ca
  } else if (region == 1 || region == 4) {
    dc20 <- dc20jp
  } else if (region == 3) {
    dc20 <- dc20ch
  } else {
    dc20 <- dc20ca
  }
  if (rrup > 80) {
    fatn <- (c20 + dc20) * (rrup - 80)
  } else if (rrup <= 80) {
    fatn <- 0
  }
  median <- exp(c0 + fmag + fdis + fflt + fhng + fsite + fsed + fhyp + fdip + fatn)
  if (t == 0) {
    ypgacb <- median
  }
  if (t < 0.25 && t != 0 && median < ypgacb) {
    y <- ypgacb
  } else {
    y <- median
  }
  return(y)
}

cy_14_raw <- function(m, rrup, rjb, rx, vs30, frv, fnm, fhw, delta, ztor, region, z1, z1r, ddpp, t) {
  c1 <- 0
  c11 <- 0
  c11b <- 0
  c1a <- 0
  c1b <- 0
  c1c <- 0
  c1d <- 0
  c2 <- 0
  c3 <- 0
  c4 <- 0
  c4a <- 0
  c5 <- 0
  c6 <- 0
  c7 <- 0
  c7b <- 0
  c8 <- 0
  c8a <- 0
  c8b <- 0
  c9 <- 0
  c9a <- 0
  c9b <- 0
  cg1 <- 0
  cg2 <- 0
  cg3 <- 0
  chm <- 0
  cm <- 0
  cn <- 0
  counter <- 0
  crb <- 0
  deltaz1 <- 0
  deltaz_tor <- 0
  e <- 0
  f1 <- 0
  f1jp <- 0
  f2 <- 0
  f3 <- 0
  f4 <- 0
  f5 <- 0
  f5jp <- 0
  f6 <- 0
  f6jp <- 0
  fatn <- 0
  fdip <- 0
  fdir <- 0
  fdis <- 0
  fflt <- 0
  fhng <- 0
  fmag <- 0
  fsite <- 0
  ftor <- 0
  g <- 0
  gjpit <- 0
  gwn <- 0
  k <- 0
  maxdir <- 0
  maxdir1 <- 0
  maxdir2 <- 0
  maxoftwo <- 0
  maxoftwo2 <- 0
  maxztord <- 0
  maxztorm <- 0
  maxztorz <- 0
  mindir <- 0
  minoftwo <- 0
  minoftwo2 <- 0
  mz <- 0
  mz1 <- 0
  mz_tor <- 0
  mz_torx <- 0
  mz_torz <- 0
  pi <- 0
  rkdepth <- 0
  s1 <- 0
  s2 <- 0
  s2jp <- 0
  s3 <- 0
  t1 <- 0
  t2 <- 0
  tanh <- 0
  x <- 0
  y <- 0
  ypga <- 0
  yref <- 0
  z <- 0
  cof <- .cof("CY14", t)
  c2 <- cof[[1]]
  c4 <- cof[[2]]
  c4a <- cof[[3]]
  crb <- cof[[4]]
  c8 <- cof[[5]]
  c8a <- cof[[6]]
  c1 <- cof[[7]]
  c1a <- cof[[8]]
  c1b <- cof[[9]]
  c1c <- cof[[10]]
  c1d <- cof[[11]]
  cn <- cof[[12]]
  cm <- cof[[13]]
  c3 <- cof[[14]]
  c5 <- cof[[15]]
  chm <- cof[[16]]
  c6 <- cof[[17]]
  c7 <- cof[[18]]
  c7b <- cof[[19]]
  c8b <- cof[[20]]
  c9 <- cof[[21]]
  c9a <- cof[[22]]
  c9b <- cof[[23]]
  c11 <- cof[[24]]
  c11b <- cof[[25]]
  cg1 <- cof[[26]]
  cg2 <- cof[[27]]
  cg3 <- cof[[28]]
  f1 <- cof[[29]]
  f2 <- cof[[30]]
  f3 <- cof[[31]]
  f4 <- cof[[32]]
  f5 <- cof[[33]]
  f6 <- cof[[34]]
  t1 <- cof[[35]]
  t2 <- cof[[36]]
  s1 <- cof[[37]]
  s2 <- cof[[38]]
  s3 <- cof[[39]]
  s2jp <- cof[[40]]
  gjpit <- cof[[41]]
  gwn <- cof[[42]]
  f1jp <- cof[[43]]
  f5jp <- cof[[44]]
  f6jp <- cof[[45]]
  pi <- 4 * atan(1)
  if (region == 1) {
    f1 <- f1jp
  }
  if (region == 1) {
    s2 <- s2jp
  }
  if (region == 1) {
    f5 <- f5jp
  }
  if (region == 1 || region == 4) {
    g <- gjpit
  }
  if (region == 3) {
    g <- gwn
  }
  if (region == 1) {
    f6 <- f6jp
  }
  fmag <- c2 * (m - 6) + (c2 - c3) / cn * log(1 + exp(cn * (cm - m)))
  if ((m - chm) > 0) {
    maxoftwo <- (m - chm)
  } else {
    maxoftwo <- 0
  }
  x <- c6 * maxoftwo
  if ((m - cg3) > 0) {
    e <- m - cg3
  } else {
    e <- 0
  }
  if ((region == 1 || region == 4) && (6 < m && m < 6.9)) {
    fatn <- gjpit * (cg1 + cg2 / ((exp(e) + exp(-e)) / 2)) * rrup
  } else if (region == 3) {
    fatn <- gwn * (cg1 + cg2 / ((exp(e) + exp(-e)) / 2)) * rrup
  } else {
    fatn <- (cg1 + cg2 / ((exp(e) + exp(-e)) / 2)) * rrup
  }
  fdis <- c4 * log(rrup + c5 * (exp(x) + exp(-x)) / 2) + (c4a - c4) * log(sqrt(rrup ^ 2 + crb ^ 2)) + fatn
  if ((m - 4.5) > 0) {
    maxoftwo2 <- m - 4.5
  } else {
    maxoftwo2 <- 0
  }
  z <- 2 * maxoftwo2
  fflt <- frv * (c1a + c1c / ((exp(z) + exp(-z)) / 2)) + fnm * (c1b + c1d / ((exp(z) + exp(-z)) / 2))
  k <- rx / c9b
  tanh <- (exp(k) - exp(-k)) / (exp(k) + exp(-k))
  if (2.704 - 1.226 * (m - 5.849) > 0) {
    maxztorm <- 2.704 - 1.226 * (m - 5.849)
  } else {
    maxztorm <- 0
  }
  if (m <= 5.849 && frv == 1) {
    mz_torx <- 2.704 * 2.704
  } else {
    mz_torx <- maxztorm * maxztorm
  }
  if (2.673 - 1.136 * (m - 4.97) > 0 && fnm == 1) {
    maxztorz <- 2.673 - 1.136 * (m - 4.97)
  } else {
    maxztorz <- 0
  }
  if (m <= 4.97 && fnm == 1) {
    mz_torz <- 2.673 * 2.673
  } else {
    mz_torz <- maxztorz * maxztorz
  }
  if ((m - 4.97) > 0 && fnm == 0 && frv == 0) {
    mz <- m - 4.97
  } else {
    mz <- 0
  }
  if (2.673 - 1.136 * (m - 4.97) > 0 && fnm == 0 && frv == 0) {
    maxztord <- 2.673 - 1.136 * mz
  } else {
    maxztord <- 0
  }
  if (frv == 1) {
    mz_tor <- mz_torx
  } else if (fnm == 1) {
    mz_tor <- mz_torz
  } else {
    mz_tor <- maxztord * maxztord
  }
  if (ztor == 999) {
    ztor <- mz_tor
  } else {
    ztor <- ztor
  }
  deltaz_tor <- ztor - mz_tor
  ftor <- (c7 + c7b / ((exp(z) + exp(-z)) / 2)) * deltaz_tor
  if (fhw == 0) {
    fhng <- 0
  } else {
    fhng <- c9 * fhw * cos(delta * pi / 180) * (c9a + (1 - c9a) * tanh) * (1 - sqrt(rjb ^ 2 + ztor ^ 2) / (rrup + 1))
  }
  if (z1 == 999) {
    z1 <- z1r
  } else {
    z1 <- z1
  }
  if (region == 1) {
    mz1 <- z1 * 1000 - exp(-5.23 / 2 * log((vs30 ^ 2 + 412.39 ^ 2) / (1360 ^ 2 + 412.39 ^ 2)))
  } else {
    mz1 <- z1 * 1000 - exp(-7.15 / 4 * log((vs30 ^ 4 + 570.94 ^ 4) / (1360 ^ 4 + 570.94 ^ 4)))
  }
  if (z1 == z1r) {
    deltaz1 <- 0
  } else {
    deltaz1 <- mz1
  }
  fdip <- (cos(delta * pi / 180) ^ 2) * (c11 + c11b / ((exp(z) + exp(-z)) / 2))
  if ((rrup - 40) > 0) {
    maxdir <- rrup - 40
  } else {
    maxdir <- 0
  }
  if (1 - maxdir / 30 > 0) {
    maxdir1 <- 1 - maxdir / 30
  } else {
    maxdir1 <- 0
  }
  if ((m - 5.5) > 0) {
    maxdir2 <- m - 5.5
  } else {
    maxdir2 <- 0
  }
  if (maxdir2 / 0.8 < 1) {
    mindir <- maxdir2 / 0.8
  } else {
    mindir <- 1
  }
  fdir <- c8 * maxdir1 * mindir * exp(-c8a * (m - c8b) ^ 2) * ddpp
  yref <- exp(c1 + fmag + fdis + fflt + fhng + ftor + fdip + fdir)
  if (log(vs30 / 1130) < 0) {
    minoftwo <- log(vs30 / 1130)
  } else {
    minoftwo <- 0
  }
  if (vs30 < 1130) {
    minoftwo2 <- vs30
  } else {
    minoftwo2 <- 1130
  }
  rkdepth <- f5 * (1 - exp(-deltaz1 / f6))
  fsite <- f1 * minoftwo + f2 * (exp(f3 * (minoftwo2 - 360)) - exp(f3 * (1130 - 360))) * log((yref + f4) / f4)
  y <- yref * exp(fsite + rkdepth)
  if (t == 0) {
    ypga <- y
  }
  if (t <= 0.3 && t != 0 && y < ypga) {
    y <- ypga
  } else {
    y <- y
  }
  return(y)
}

cy14_stdev_raw <- function(m, rrup, rjb, rx, vs30, frv, fnm, fhw, delta, ztor, region, z1, ddpp, vs30flag, t) {
  b <- 0
  c1 <- 0
  c11 <- 0
  c11b <- 0
  c1a <- 0
  c1b <- 0
  c1c <- 0
  c1d <- 0
  c2 <- 0
  c3 <- 0
  c4 <- 0
  c4a <- 0
  c5 <- 0
  c6 <- 0
  c7 <- 0
  c7b <- 0
  c8 <- 0
  c8a <- 0
  c8b <- 0
  c9 <- 0
  c9a <- 0
  c9b <- 0
  cg1 <- 0
  cg2 <- 0
  cg3 <- 0
  chm <- 0
  cm <- 0
  cn <- 0
  counter <- 0
  crb <- 0
  deltaz_tor <- 0
  e <- 0
  f1 <- 0
  f1jp <- 0
  f2 <- 0
  f3 <- 0
  f4 <- 0
  f5 <- 0
  f5jp <- 0
  f6 <- 0
  f6jp <- 0
  fatn <- 0
  fdip <- 0
  fdir <- 0
  fdis <- 0
  fflt <- 0
  fhng <- 0
  finf <- 0
  fmag <- 0
  fmeas <- 0
  ftor <- 0
  g <- 0
  gjpit <- 0
  gwn <- 0
  k <- 0
  maxdir <- 0
  maxdir1 <- 0
  maxdir2 <- 0
  maxoftwo <- 0
  maxoftwo2 <- 0
  maxt <- 0
  maxztord <- 0
  maxztorm <- 0
  maxztorz <- 0
  mindir <- 0
  minoftwo <- 0
  minoftwo2 <- 0
  mint <- 0
  mz <- 0
  mz_tor <- 0
  mz_torx <- 0
  mz_torz <- 0
  nl0 <- 0
  phi <- 0
  pi <- 0
  s <- 0
  s1 <- 0
  s2 <- 0
  s2jp <- 0
  s3 <- 0
  sigma <- 0
  sigma_nl0 <- 0
  sigma_nl0_s <- 0
  t1 <- 0
  t2 <- 0
  tanh <- 0
  tau <- 0
  x <- 0
  yref <- 0
  z <- 0
  cof <- .cof("CY14", t)
  c2 <- cof[[1]]
  c4 <- cof[[2]]
  c4a <- cof[[3]]
  crb <- cof[[4]]
  c8 <- cof[[5]]
  c8a <- cof[[6]]
  c1 <- cof[[7]]
  c1a <- cof[[8]]
  c1b <- cof[[9]]
  c1c <- cof[[10]]
  c1d <- cof[[11]]
  cn <- cof[[12]]
  cm <- cof[[13]]
  c3 <- cof[[14]]
  c5 <- cof[[15]]
  chm <- cof[[16]]
  c6 <- cof[[17]]
  c7 <- cof[[18]]
  c7b <- cof[[19]]
  c8b <- cof[[20]]
  c9 <- cof[[21]]
  c9a <- cof[[22]]
  c9b <- cof[[23]]
  c11 <- cof[[24]]
  c11b <- cof[[25]]
  cg1 <- cof[[26]]
  cg2 <- cof[[27]]
  cg3 <- cof[[28]]
  f1 <- cof[[29]]
  f2 <- cof[[30]]
  f3 <- cof[[31]]
  f4 <- cof[[32]]
  f5 <- cof[[33]]
  f6 <- cof[[34]]
  t1 <- cof[[35]]
  t2 <- cof[[36]]
  s1 <- cof[[37]]
  s2 <- cof[[38]]
  s3 <- cof[[39]]
  s2jp <- cof[[40]]
  gjpit <- cof[[41]]
  gwn <- cof[[42]]
  f1jp <- cof[[43]]
  f5jp <- cof[[44]]
  f6jp <- cof[[45]]
  pi <- 4 * atan(1)
  if (region == 1) {
    f1 <- f1jp
  }
  if (region == 1) {
    s2 <- s2jp
  }
  if (region == 1) {
    f5 <- f5jp
  }
  if (region == 1 || region == 4) {
    g <- gjpit
  }
  if (region == 3) {
    g <- gwn
  }
  if (region == 1) {
    f6 <- f6jp
  }
  fmag <- c2 * (m - 6) + (c2 - c3) / cn * log(1 + exp(cn * (cm - m)))
  if ((m - chm) > 0) {
    maxoftwo <- (m - chm)
  } else {
    maxoftwo <- 0
  }
  x <- c6 * maxoftwo
  if ((m - cg3) > 0) {
    e <- m - cg3
  } else {
    e <- 0
  }
  if ((region == 1 || region == 4) && (6 < m && m < 6.9)) {
    fatn <- gjpit * (cg1 + cg2 / ((exp(e) + exp(-e)) / 2)) * rrup
  } else if (region == 3) {
    fatn <- gwn * (cg1 + cg2 / ((exp(e) + exp(-e)) / 2)) * rrup
  } else {
    fatn <- (cg1 + cg2 / ((exp(e) + exp(-e)) / 2)) * rrup
  }
  fdis <- c4 * log(rrup + c5 * (exp(x) + exp(-x)) / 2) + (c4a - c4) * log(sqrt(rrup ^ 2 + crb ^ 2)) + fatn
  if ((m - 4.5) > 0) {
    maxoftwo2 <- m - 4.5
  } else {
    maxoftwo2 <- 0
  }
  z <- 2 * maxoftwo2
  fflt <- frv * (c1a + c1c / ((exp(z) + exp(-z)) / 2)) + fnm * (c1b + c1d / ((exp(z) + exp(-z)) / 2))
  k <- rx / c9b
  tanh <- (exp(k) - exp(-k)) / (exp(k) + exp(-k))
  if (2.704 - 1.226 * (m - 5.849) > 0) {
    maxztorm <- 2.704 - 1.226 * (m - 5.849)
  } else {
    maxztorm <- 0
  }
  if (m <= 5.849 && frv == 1) {
    mz_torx <- 2.704 * 2.704
  } else {
    mz_torx <- maxztorm * maxztorm
  }
  if (2.673 - 1.136 * (m - 4.97) > 0 && fnm == 1) {
    maxztorz <- 2.673 - 1.136 * (m - 4.97)
  } else {
    maxztorz <- 0
  }
  if (m <= 4.97 && fnm == 1) {
    mz_torz <- 2.673 * 2.673
  } else {
    mz_torz <- maxztorz * maxztorz
  }
  if ((m - 4.97) > 0 && fnm == 0 && frv == 0) {
    mz <- m - 4.97
  } else {
    mz <- 0
  }
  if (2.673 - 1.136 * (m - 4.97) > 0 && fnm == 0 && frv == 0) {
    maxztord <- 2.673 - 1.136 * mz
  } else {
    maxztord <- 0
  }
  if (frv == 1) {
    mz_tor <- mz_torx
  } else if (fnm == 1) {
    mz_tor <- mz_torz
  } else {
    mz_tor <- maxztord * maxztord
  }
  if (ztor == 999) {
    ztor <- mz_tor
  } else {
    ztor <- ztor
  }
  deltaz_tor <- ztor - mz_tor
  ftor <- (c7 + c7b / ((exp(z) + exp(-z)) / 2)) * deltaz_tor
  if (fhw == 0) {
    fhng <- 0
  } else {
    fhng <- c9 * fhw * cos(delta * pi / 180) * (c9a + (1 - c9a) * tanh) * (1 - sqrt(rjb ^ 2 + ztor ^ 2) / (rrup + 1))
  }
  fdip <- (cos(delta * pi / 180) ^ 2) * (c11 + c11b / ((exp(z) + exp(-z)) / 2))
  if ((rrup - 40) > 0) {
    maxdir <- rrup - 40
  } else {
    maxdir <- 0
  }
  if (1 - maxdir / 30 > 0) {
    maxdir1 <- 1 - maxdir / 30
  } else {
    maxdir1 <- 0
  }
  if ((m - 5.5) > 0) {
    maxdir2 <- m - 5.5
  } else {
    maxdir2 <- 0
  }
  if (maxdir2 / 0.8 < 1) {
    mindir <- maxdir2 / 0.8
  } else {
    mindir <- 1
  }
  fdir <- c8 * maxdir1 * mindir * exp(-c8a * (m - c8b) ^ 2) * ddpp
  yref <- exp(c1 + fmag + fdis + fflt + fhng + ftor + fdip + fdir)
  if (log(vs30 / 1130) < 0) {
    minoftwo <- log(vs30 / 1130)
  } else {
    minoftwo <- 0
  }
  if (vs30 < 1130) {
    minoftwo2 <- vs30
  } else {
    minoftwo2 <- 1130
  }
  b <- f2 * (exp(f3 * (minoftwo2 - 360)) - exp(f3 * (1130 - 360)))
  nl0 <- b * (yref / (yref + f4))
  if (m >= 5) {
    maxt <- m
  } else {
    maxt <- 5
  }
  if (maxt < 6.5) {
    mint <- maxt
  } else {
    mint <- 6.5
  }
  tau <- t1 + (t2 - t1) / 1.5 * (mint - 5)
  sigma_nl0_s <- s1 + (s2 - s1) / 1.5 * (mint - 5)
  if (vs30flag == 1) {
    fmeas <- 1
  } else if (vs30flag == 0) {
    finf <- 1
  }
  sigma_nl0 <- sigma_nl0_s * sqrt(0.7 * fmeas + finf * s3 + (1 + nl0) ^ 2)
  sigma <- sqrt((tau * (1 + nl0)) ^ 2 + sigma_nl0 ^ 2)
  phi <- sigma_nl0
  tau <- (tau * (1 + nl0))
  s <- sigma
  return(s)
}

ask_14_raw <- function(m, rrup, rjb, rx, frv, fnm, fhw, fas, ztor, w, dip, vs30, vs30flag, z1, ry0, region, t) {
  a1 <- 0
  a10 <- 0
  a11 <- 0
  a12 <- 0
  a13 <- 0
  a14 <- 0
  a15 <- 0
  a16 <- 0
  a17 <- 0
  a2 <- 0
  a25 <- 0
  a28 <- 0
  a29 <- 0
  a2hw <- 0
  a3 <- 0
  a31 <- 0
  a36 <- 0
  a37 <- 0
  a38 <- 0
  a39 <- 0
  a4 <- 0
  a40 <- 0
  a41 <- 0
  a42 <- 0
  a43 <- 0
  a44 <- 0
  a45 <- 0
  a46 <- 0
  a5 <- 0
  a6 <- 0
  a7 <- 0
  a8 <- 0
  b <- 0
  bq <- 0
  br <- 0
  bs <- 0
  by <- 0
  c <- 0
  c4 <- 0
  c4m <- 0
  counter <- 0
  crjb <- 0
  f1 <- 0
  f10 <- 0
  f11 <- 0
  f12 <- 0
  f13 <- 0
  f4 <- 0
  f5 <- 0
  f6 <- 0
  f7 <- 0
  f8 <- 0
  h1 <- 0
  h2 <- 0
  h3 <- 0
  m1 <- 0
  m1z <- 0
  m2 <- 0
  m2z <- 0
  maxm <- 0
  maxval <- 0
  maxz <- 0
  n <- 0
  pi <- 0
  r <- 0
  r1 <- 0
  r2 <- 0
  rd <- 0
  reg <- 0
  rvs <- 0
  ry1 <- 0
  s1 <- 0
  s1v <- 0
  s2 <- 0
  s2v <- 0
  s3 <- 0
  s4 <- 0
  s5 <- 0
  s6 <- 0
  sa1180 <- 0
  t1 <- 0
  t2 <- 0
  t3 <- 0
  t4 <- 0
  t5 <- 0
  v1 <- 0
  vlin <- 0
  vs30star <- 0
  vs30star1180 <- 0
  west <- 0
  x1 <- 0
  x1z <- 0
  x2 <- 0
  x2z <- 0
  y <- 0
  y1 <- 0
  y1z <- 0
  y2 <- 0
  y2z <- 0
  z1r <- 0
  ztord <- 0
  cof <- .cof("ASK14", t)
  vlin <- cof[[1]]
  b <- cof[[2]]
  n <- cof[[3]]
  m1 <- cof[[4]]
  c <- cof[[5]]
  c4 <- cof[[6]]
  a1 <- cof[[7]]
  a2 <- cof[[8]]
  a3 <- cof[[9]]
  a4 <- cof[[10]]
  a5 <- cof[[11]]
  a6 <- cof[[12]]
  a7 <- cof[[13]]
  a8 <- cof[[14]]
  a10 <- cof[[15]]
  a11 <- cof[[16]]
  a12 <- cof[[17]]
  a13 <- cof[[18]]
  a14 <- cof[[19]]
  a15 <- cof[[20]]
  a16 <- cof[[21]]
  a17 <- cof[[22]]
  a43 <- cof[[23]]
  a44 <- cof[[24]]
  a45 <- cof[[25]]
  a46 <- cof[[26]]
  a25 <- cof[[27]]
  a28 <- cof[[28]]
  a29 <- cof[[29]]
  a31 <- cof[[30]]
  a36 <- cof[[31]]
  a37 <- cof[[32]]
  a38 <- cof[[33]]
  a39 <- cof[[34]]
  a40 <- cof[[35]]
  a41 <- cof[[36]]
  a42 <- cof[[37]]
  s1 <- cof[[38]]
  s2 <- cof[[39]]
  s3 <- cof[[40]]
  s4 <- cof[[41]]
  s1v <- cof[[42]]
  s2v <- cof[[43]]
  s5 <- cof[[44]]
  s6 <- cof[[45]]
  a2hw <- 0.2
  h1 <- 0.25
  h2 <- 1.5
  h3 <- -0.75
  m2 <- 5
  n <- 1.5
  a7 <- 0
  crjb <- 999.9
  pi <- 4 * atan(1)
  if (ztor == 999) {
    if (frv == 1) {
      maxm <- m - 5.849
      if (0 > maxm) {
        maxm <- 0
      }
      maxz <- 2.704 - 1.226 * maxm
      if (0 > maxz) {
        maxz <- 0
      }
    } else {
      maxm <- m - 4.97
      if (0 > maxm) {
        maxm <- 0
      }
      maxz <- 2.673 - 1.136 * maxm
      if (0 > maxz) {
        maxz <- 0
      }
    }
    ztor <- maxz ^ 2
  }
  if (18 / sin(dip * pi / 180) < 10 ^ (-1.75 + 0.45 * m)) {
    west <- 18 / sin(dip * pi / 180)
  } else {
    west <- 10 ^ (-1.75 + 0.45 * m)
  }
  if (w == 999) {
    w <- west
  } else {
    w <- w
  }
  m1z <- 5
  m2z <- 7.2
  maxval <- 7.8
  if (m <= m1z) {
    ztord <- maxval
  } else if (m <= m2z) {
    ztord <- maxval - (maxval / (m2 - m1)) * (m - m1)
  } else {
    ztord <- 0
  }
  if (ztor == 999) {
    ztor <- ztord
  } else {
    ztor <- ztor
  }
  if (m >= 5) {
    c4m <- c4
  } else if (m >= 4) {
    c4m <- c4 - (c4 - 1) * (5 - m)
  } else {
    c4m <- 1
  }
  r <- sqrt(rrup ^ 2 + c4m ^ 2)
  if (m < m2) {
    f1 <- a1 + a4 * (m2 - m1) + a8 * (8.5 - m2) ^ 2 + a6 * (m - m2) + a7 * (m - m2) ^ 2 + (a2 + a3 * (m2 - m1)) * log(r) + a17 * rrup
  } else if (m < m1) {
    f1 <- a1 + a4 * (m - m1) + a8 * (8.5 - m) ^ 2 + (a2 + a3 * (m - m1)) * log(r) + a17 * rrup
  } else {
    f1 <- a1 + a5 * (m - m1) + a8 * (8.5 - m) ^ 2 + (a2 + a3 * (m - m1)) * log(r) + a17 * rrup
  }
  if (t >= 3) {
    v1 <- 800
  } else if (t > 0.5) {
    v1 <- exp(-0.35 * log(t / 0.5) + log(1500))
  } else {
    v1 <- 1500
  }
  if (vs30 < v1) {
    vs30star <- vs30
  } else {
    vs30star <- v1
  }
  if (ztor <= 20) {
    f6 <- a15 * ztor / 20
  } else if (ztor > 20) {
    f6 <- a15
  }
  if (m < 4) {
    f7 <- 0
  } else if (m <= 5) {
    f7 <- a11 * (m - 4)
  } else {
    f7 <- a11
  }
  if (m < 4) {
    f8 <- 0
  } else if (m <= 5) {
    f8 <- a12 * (m - 4)
  } else {
    f8 <- a12
  }
  r1 <- w * cos(dip * pi / 180)
  r2 <- 3 * r1
  ry1 <- rx * tan(20 * pi / 180)
  if (dip > 30) {
    t1 <- (90 - dip) / 45
  } else {
    t1 <- 60 / 45
  }
  if (m > 6.5) {
    t2 <- 1 + a2hw * (m - 6.5)
  } else if (m > 5.5) {
    t2 <- 1 + a2hw * (m - 6.5) - (1 - a2hw) * (m - 6.5) ^ 2
  } else {
    t2 <- 0
  }
  if (rx <= r1) {
    t3 <- h1 + h2 * (rx / r1) + h3 * (rx / r1) ^ 2
  } else if (rx < r2) {
    t3 <- 1 - (rx - r1) / (r2 - r1)
  } else {
    t3 <- 0
  }
  if (ztor < 10) {
    t4 <- 1 - ztor ^ 2 / 100
  } else {
    t4 <- 0
  }
  if (ry0 != 999) {
    if (ry0 < ry1) {
      t5 <- 1
    } else if ((ry0 - ry1) < 5) {
      t5 <- 1 - (ry0 - ry1) / 5
    } else {
      t5 <- 0
    }
  } else {
    if (rjb == 0) {
      t5 <- 1
    } else if (rjb < 30) {
      t5 <- 1 - rjb / 30
    } else {
      t5 <- 0
    }
  }
  if (fhw == 1) {
    f4 <- a13 * t1 * t2 * t3 * t4 * t5
  } else {
    f4 <- 0
  }
  if (region == 2) {
    f12 <- a31 * log(vs30star / vlin)
  } else {
    f12 <- 0
  }
  if (region == 1) {
    br <- (a41 + (1180 - 850) * (a42 - a41) / (1150 - 850))
  } else if (region == 2) {
    br <- a31 * log(1180 / vlin)
  } else {
    br <- 0
  }
  if (region == 1) {
    by <- a29
  } else if (region == 3) {
    by <- a28
  } else if (region == 2) {
    by <- a25
  } else {
    by <- 0
  }
  bs <- by * rrup + br
  if (1180 >= v1) {
    vs30star1180 <- v1
  } else {
    vs30star1180 <- 1180
  }
  bq <- (a10 + b * n) * log(vs30star1180 / vlin)
  sa1180 <- exp(f1 + f6 + frv * f7 + fnm * f8 + fhw * f4 + bq + bs)
  if (vs30 < vlin) {
    f5 <- a10 * log(vs30star / vlin) - b * log(sa1180 + c) + b * log(sa1180 + c * (vs30star / vlin) ^ n)
  } else {
    f5 <- (a10 + b * n) * log(vs30star / vlin)
  }
  if (region == 1) {
    z1r <- exp(-5.23 / 2 * log((vs30 ^ 2 + 412 ^ 2) / (1360 ^ 2 + 412 ^ 2))) / 1000
  } else {
    z1r <- exp(-7.67 / 4 * log((vs30 ^ 4 + 610 ^ 4) / (1360 ^ 4 + 610 ^ 4))) / 1000
  }
  if (vs30 <= 150) {
    y1z <- a43
    y2z <- a43
    x1z <- 50
    x2z <- 150
  } else if (vs30 <= 250) {
    y1z <- a43
    y2z <- a44
    x1z <- 150
    x2z <- 250
  } else if (vs30 <= 400) {
    y1z <- a44
    y2z <- a45
    x1z <- 250
    x2z <- 400
  } else if (vs30 <= 700) {
    y1z <- a45
    y2z <- a46
    x1z <- 400
    x2z <- 700
  } else {
    y1z <- a46
    y2z <- a46
    x1z <- 700
    x2z <- 1000
  }
  if (vs30 == 1180) {
    f10 <- 0
  } else {
    f10 <- (y1z + (vs30 - x1z) * (y2z - y1z) / (x2z - x1z)) * log((z1 + 0.01) / (z1r + 0.01))
  }
  if (fas == 0) {
    f11 <- 0
  }
  if (region == 1) {
    if (vs30 < 150) {
      y1 <- a36
      y2 <- a36
      x1 <- 50
      x2 <- 150
    } else if (vs30 < 250) {
      y1 <- a36
      y2 <- a37
      x1 <- 150
      x2 <- 250
    } else if (vs30 < 350) {
      y1 <- a37
      y2 <- a38
      x1 <- 250
      x2 <- 350
    } else if (vs30 < 450) {
      y1 <- a38
      y2 <- a39
      x1 <- 350
      x2 <- 450
    } else if (vs30 < 600) {
      y1 <- a39
      y2 <- a40
      x1 <- 450
      x2 <- 600
    } else if (vs30 < 850) {
      y1 <- a40
      y2 <- a41
      x1 <- 600
      x2 <- 850
    } else if (vs30 < 1150) {
      y1 <- a41
      y2 <- a42
      x1 <- 850
      x2 <- 1150
    } else {
      y1 <- a42
      y2 <- a42
      x1 <- 1150
      x2 <- 3000
    }
    f13 <- y1 + (y2 - y1) / (x2 - x1) * (vs30 - x1)
  }
  if (region == 2) {
    reg <- f12 + a25 * rrup
  } else if (region == 3) {
    reg <- a28 * rrup
  } else if (region == 1) {
    reg <- f13 + a29 * rrup
  } else {
    reg <- 0
  }
  if (region == 1) {
    rvs <- f13
  } else if (region == 2) {
    rvs <- f12
  } else {
    rvs <- 0
  }
  rd <- rvs + by * rrup
  y <- exp(f1 + frv * f7 + fnm * f8 + fas * f11 + f5 + fhw * f4 + f6 + f10 + rd)
  return(y)
}

ask14_z1 <- function(vs30, region, z1) {
  y <- 0
  if (z1 == 999) {
    if (region == 1) {
      z1 <- exp(-5.23 / 2 * log((vs30 ^ 2 + 412 ^ 2) / (1360 ^ 2 + 412 ^ 2))) / 1000
    } else {
      z1 <- exp((-7.67 / 4) * log((vs30 ^ 4 + 610 ^ 4) / (1360 ^ 4 + 610 ^ 4))) / 1000
    }
  } else {
    z1 <- z1
  }
  y <- z1
  return(y)
}

ask14_stdev_raw <- function(m, rrup, rjb, rx, frv, fnm, fhw, fas, ztor, w, dip, vs30, vs30flag, z1, ry0, region, t) {
  a1 <- 0
  a10 <- 0
  a11 <- 0
  a12 <- 0
  a13 <- 0
  a14 <- 0
  a15 <- 0
  a16 <- 0
  a17 <- 0
  a2 <- 0
  a25 <- 0
  a28 <- 0
  a29 <- 0
  a2hw <- 0
  a3 <- 0
  a31 <- 0
  a36 <- 0
  a37 <- 0
  a38 <- 0
  a39 <- 0
  a4 <- 0
  a40 <- 0
  a41 <- 0
  a42 <- 0
  a43 <- 0
  a44 <- 0
  a45 <- 0
  a46 <- 0
  a5 <- 0
  a6 <- 0
  a7 <- 0
  a8 <- 0
  b <- 0
  bq <- 0
  br <- 0
  bs <- 0
  by <- 0
  c <- 0
  c4 <- 0
  c4m <- 0
  counter <- 0
  crjb <- 0
  f1 <- 0
  f4 <- 0
  f6 <- 0
  f7 <- 0
  f8 <- 0
  h1 <- 0
  h2 <- 0
  h3 <- 0
  m1 <- 0
  m1z <- 0
  m2 <- 0
  m2z <- 0
  maxm <- 0
  maxval <- 0
  maxz <- 0
  n <- 0
  phi <- 0
  phia <- 0
  phib <- 0
  pi <- 0
  r <- 0
  r1 <- 0
  r2 <- 0
  ratio <- 0
  ry1 <- 0
  s1 <- 0
  s1v <- 0
  s2 <- 0
  s2v <- 0
  s3 <- 0
  s4 <- 0
  s5 <- 0
  s6 <- 0
  sa1180 <- 0
  samp <- 0
  sd <- 0
  sigma <- 0
  t1 <- 0
  t2 <- 0
  t3 <- 0
  t4 <- 0
  t5 <- 0
  tau <- 0
  taua <- 0
  taub <- 0
  v1 <- 0
  vlin <- 0
  vs30star <- 0
  vs30star1180 <- 0
  west <- 0
  ztord <- 0
  cof <- .cof("ASK14", t)
  vlin <- cof[[1]]
  b <- cof[[2]]
  n <- cof[[3]]
  m1 <- cof[[4]]
  c <- cof[[5]]
  c4 <- cof[[6]]
  a1 <- cof[[7]]
  a2 <- cof[[8]]
  a3 <- cof[[9]]
  a4 <- cof[[10]]
  a5 <- cof[[11]]
  a6 <- cof[[12]]
  a7 <- cof[[13]]
  a8 <- cof[[14]]
  a10 <- cof[[15]]
  a11 <- cof[[16]]
  a12 <- cof[[17]]
  a13 <- cof[[18]]
  a14 <- cof[[19]]
  a15 <- cof[[20]]
  a16 <- cof[[21]]
  a17 <- cof[[22]]
  a43 <- cof[[23]]
  a44 <- cof[[24]]
  a45 <- cof[[25]]
  a46 <- cof[[26]]
  a25 <- cof[[27]]
  a28 <- cof[[28]]
  a29 <- cof[[29]]
  a31 <- cof[[30]]
  a36 <- cof[[31]]
  a37 <- cof[[32]]
  a38 <- cof[[33]]
  a39 <- cof[[34]]
  a40 <- cof[[35]]
  a41 <- cof[[36]]
  a42 <- cof[[37]]
  s1 <- cof[[38]]
  s2 <- cof[[39]]
  s3 <- cof[[40]]
  s4 <- cof[[41]]
  s1v <- cof[[42]]
  s2v <- cof[[43]]
  s5 <- cof[[44]]
  s6 <- cof[[45]]
  h1 <- 0.25
  h2 <- 1.5
  h3 <- -0.75
  m2 <- 5
  n <- 1.5
  a7 <- 0
  a2hw <- 0.2
  samp <- 0.4
  crjb <- 999.9
  pi <- 4 * atan(1)
  if (ztor == 999) {
    if (frv == 1) {
      maxm <- m - 5.849
      if (0 > maxm) {
        maxm <- 0
      }
      maxz <- 2.704 - 1.226 * maxm
      if (0 > maxz) {
        maxz <- 0
      }
    } else {
      maxm <- m - 4.97
      if (0 > maxm) {
        maxm <- 0
      }
      maxz <- 2.673 - 1.136 * maxm
      if (0 > maxz) {
        maxz <- 0
      }
    }
    ztor <- maxz ^ 2
  }
  if (18 / sin(dip * pi / 180) < 10 ^ (-1.75 + 0.45 * m)) {
    west <- 18 / sin(dip * pi / 180)
  } else {
    west <- 10 ^ (-1.75 + 0.45 * m)
  }
  if (w == 999) {
    w <- west
  } else {
    w <- w
  }
  m1z <- 5
  m2z <- 7.2
  maxval <- 7.8
  if (m <= m1z) {
    ztord <- maxval
  } else if (m <= m2z) {
    ztord <- maxval - (maxval / (m2 - m1)) * (m - m1)
  } else {
    ztord <- 0
  }
  if (ztor == 999) {
    ztor <- ztord
  } else {
    ztor <- ztor
  }
  if (m >= 5) {
    c4m <- c4
  } else if (m >= 4) {
    c4m <- c4 - (c4 - 1) * (5 - m)
  } else {
    c4m <- 1
  }
  r <- sqrt(rrup ^ 2 + c4m ^ 2)
  if (m < m2) {
    f1 <- a1 + a4 * (m2 - m1) + a8 * (8.5 - m2) ^ 2 + a6 * (m - m2) + a7 * (m - m2) ^ 2 + (a2 + a3 * (m2 - m1)) * log(r) + a17 * rrup
  } else if (m < m1) {
    f1 <- a1 + a4 * (m - m1) + a8 * (8.5 - m) ^ 2 + (a2 + a3 * (m - m1)) * log(r) + a17 * rrup
  } else {
    f1 <- a1 + a5 * (m - m1) + a8 * (8.5 - m) ^ 2 + (a2 + a3 * (m - m1)) * log(r) + a17 * rrup
  }
  if (t >= 3) {
    v1 <- 800
  } else if (t > 0.5) {
    v1 <- exp(-0.35 * log(t / 0.5) + log(1500))
  } else {
    v1 <- 1500
  }
  if (vs30 < v1) {
    vs30star <- vs30
  } else {
    vs30star <- v1
  }
  if (m < 4) {
    f7 <- 0
  } else if (m <= 5) {
    f7 <- a11 * (m - 4)
  } else {
    f7 <- a11
  }
  if (m < 4) {
    f8 <- 0
  } else if (m <= 5) {
    f8 <- a12 * (m - 4)
  } else {
    f8 <- a12
  }
  r1 <- w * cos(dip * pi / 180)
  r2 <- 3 * r1
  ry1 <- rx * tan(20 * pi / 180)
  if (dip > 30) {
    t1 <- (90 - dip) / 45
  } else {
    t1 <- 60 / 45
  }
  if (m > 6.5) {
    t2 <- 1 + a2hw * (m - 6.5)
  } else if (m > 5.5) {
    t2 <- 1 + a2hw * (m - 6.5) - (1 - a2hw) * (m - 6.5) ^ 2
  } else {
    t2 <- 0
  }
  if (rx <= r1) {
    t3 <- h1 + h2 * (rx / r1) + h3 * (rx / r1) ^ 2
  } else if (rx < r2) {
    t3 <- 1 - (rx - r1) / (r2 - r1)
  } else {
    t3 <- 0
  }
  if (ztor < 10) {
    t4 <- 1 - ztor ^ 2 / 100
  } else {
    t4 <- 0
  }
  if (ry0 != 999) {
    if (ry0 < ry1) {
      t5 <- 1
    } else if ((ry0 - ry1) < 5) {
      t5 <- 1 - (ry0 - ry1) / 5
    } else {
      t5 <- 0
    }
  } else {
    if (rjb == 0) {
      t5 <- 1
    } else if (rjb < 30) {
      t5 <- 1 - rjb / 30
    } else {
      t5 <- 0
    }
  }
  if (fhw == 1) {
    f4 <- a13 * t1 * t2 * t3 * t4 * t5
  } else {
    f4 <- 0
  }
  if (region == 1) {
    br <- (a41 + (1180 - 850) * (a42 - a41) / (1150 - 850))
  } else if (region == 2) {
    br <- a31 * log(1180 / vlin)
  } else {
    br <- 0
  }
  if (region == 1) {
    by <- a29
  } else if (region == 3) {
    by <- a28
  } else if (region == 2) {
    by <- a25
  } else {
    by <- 0
  }
  bs <- by * rrup + br
  if (1180 >= v1) {
    vs30star1180 <- v1
  } else {
    vs30star1180 <- 1180
  }
  bq <- (a10 + b * n) * log(vs30star1180 / vlin)
  if (ztor <= 20) {
    f6 <- a15 * ztor / 20
  } else if (ztor > 20) {
    f6 <- a15
  }
  sa1180 <- exp(f1 + f6 + frv * f7 + fnm * f8 + fhw * f4 + bq + bs)
  if (region != 1) {
    if (vs30flag == 0) {
      s1 <- s1
      s2 <- s2
    } else if (vs30flag == 1) {
      s1 <- s1v
      s2 <- s2v
    }
    if (m < 4) {
      phia <- s1
    } else if (m <= 6) {
      phia <- s1 + (s2 - s1) / 2 * (m - 4)
    } else {
      phia <- s2
    }
  } else {
    if (rrup < 30) {
      phia <- s5
    } else if (rrup <= 80) {
      phia <- s5 + (s6 - s5) / 50 * (rrup - 30)
    } else if (rrup > 80) {
      phia <- s6
    }
  }
  if (m < 5) {
    taua <- s3
  } else if (m <= 7) {
    taua <- s3 + (s4 - s3) / 2 * (m - 5)
  } else {
    taua <- s4
  }
  taub <- taua
  phib <- sqrt(phia ^ 2 - samp ^ 2)
  if (vs30 >= vlin) {
    ratio <- 0
  } else {
    ratio <- b * sa1180 * (-1 / (sa1180 + c) + 1 / (sa1180 + c * (vs30 / vlin) ^ n))
  }
  tau <- taub * (1 + ratio)
  phi <- sqrt(phib ^ 2 * (1 + ratio) ^ 2 + samp ^ 2)
  sigma <- sqrt(tau ^ 2 + phi ^ 2)
  sd <- sigma
  return(sd)
}

